image:
  file: .gitpod.dockerfile
tasks:
- before: cp .gitpod.aliases ~/.aliases && cat .gitpod.bashrc >> ~/.bashrc
- init: npm install
- command: npm run watch
- command: npm run prettier-watch
- command: ts-node
